---

- name: Naive assertion of proper listen address
  assert:
    that:
      - "':' in redis_exporter_web_listen_address"

- name: Fail on unsupported init systems
  fail:
    msg: "This module only works with systemd"
  when: ansible_service_mgr != 'systemd'
