---

- name: Naive assertion of proper listen address
  assert:
    that:
      - "':' in redis_exporter_web_listen_address"

- name: Naive assertion for ansible_service_mgr (fail on unsupported init systems)
  assert:
    that:
      - ansible_service_mgr == "systemd"
    fail_msg: "this role work only with systemd distributives"
